// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnfusujqulsqoadthoke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZnVzdWpxdWxzcW9hZHRob2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjYwMTUsImV4cCI6MjA2MDIwMjAxNX0.hhUZs_y_8Kn-VteXlAS8nZdFnPmjrClnRU4Z59b9YpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);